#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# Phase 2 — Provision Azure resources.  Run ONCE.
#
#   bash azure/setup.sh
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Azure CLI from project venv (installed there, not system-wide) ───────────
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
AZ="$REPO_ROOT/.venv/bin/python3 -m azure.cli"

# ── Config ───────────────────────────────────────────────────────────────────
RESOURCE_GROUP="talk-radio-rg"
LOCATION="australiaeast"
STORAGE_ACCOUNT="talkradiostore$RANDOM"   # must be globally unique, lowercase
FILE_SHARE="talk-radio-data"
SHARE_QUOTA_GB=10
ENV_FILE="$REPO_ROOT/azure/.azure-env"

# ── Login check ───────────────────────────────────────────────────────────────
$AZ account show >/dev/null 2>&1 || {
    echo "Not logged in — opening browser login..."
    $AZ login
}

echo "▶  Subscription : $($AZ account show --query name -o tsv)"
echo "▶  Region       : $LOCATION"
echo "▶  Resource group: $RESOURCE_GROUP"
echo "▶  Storage acct : $STORAGE_ACCOUNT"
read -p "Continue? [y/N] " yn
[[ "$yn" =~ ^[Yy]$ ]] || { echo "aborted"; exit 0; }

# ── 1. Resource group ─────────────────────────────────────────────────────────
echo "▶  Creating resource group..."
$AZ group create -n "$RESOURCE_GROUP" -l "$LOCATION" -o none

# ── 2. Storage account (Standard LRS, hot tier) ───────────────────────────────
echo "▶  Creating storage account $STORAGE_ACCOUNT..."
$AZ storage account create \
    --name "$STORAGE_ACCOUNT" \
    --resource-group "$RESOURCE_GROUP" \
    --location "$LOCATION" \
    --sku Standard_LRS \
    --kind StorageV2 \
    --access-tier Hot \
    --min-tls-version TLS1_2 \
    -o none

STORAGE_KEY=$($AZ storage account keys list \
    --resource-group "$RESOURCE_GROUP" \
    --account-name "$STORAGE_ACCOUNT" \
    --query '[0].value' -o tsv)

# ── 3. File share (10 GB — fits transcripts + chroma_db + results) ────────────
echo "▶  Creating file share $FILE_SHARE (${SHARE_QUOTA_GB}GB)..."
$AZ storage share-rm create \
    --resource-group "$RESOURCE_GROUP" \
    --storage-account "$STORAGE_ACCOUNT" \
    --name "$FILE_SHARE" \
    --quota "$SHARE_QUOTA_GB" \
    -o none

# ── 4. Container Apps environment ─────────────────────────────────────────────
echo "▶  Installing Container Apps CLI extension..."
$AZ extension add --name containerapp --upgrade -y -o none 2>/dev/null || true
$AZ provider register --namespace Microsoft.App               --wait -o none
$AZ provider register --namespace Microsoft.OperationalInsights --wait -o none

echo "▶  Creating Container Apps environment (takes ~3 min)..."
$AZ containerapp env create \
    --name talk-radio-env \
    --resource-group "$RESOURCE_GROUP" \
    --location "$LOCATION" \
    -o none

# ── 5. Save config for upload_data.sh + deploy.sh ────────────────────────────
cat > "$ENV_FILE" <<EOF
# Generated by azure/setup.sh — already in .gitignore, do NOT commit
RESOURCE_GROUP="$RESOURCE_GROUP"
LOCATION="$LOCATION"
STORAGE_ACCOUNT="$STORAGE_ACCOUNT"
STORAGE_KEY="$STORAGE_KEY"
FILE_SHARE="$FILE_SHARE"
CONTAINERAPP_ENV="talk-radio-env"
CONTAINERAPP_NAME="talk-radio-app"
EOF

echo
echo "======================================================"
echo "  Phase 2 complete!"
echo "  Config saved to: azure/.azure-env"
echo ""
echo "  Next steps:"
echo "  1) bash azure/upload_data.sh   # Phase 3 — upload data"
echo "  2) bash azure/deploy.sh        # Phase 4+5 — build & deploy"
echo "======================================================"
